;[pytest]
;
;addopts = --headed
;          --browser=chromium
;          --video=retain-on-failure
;          --screenshot=only-on-failure
;          --tracing=retain-on-failure
;          --html=myreport.html --self-contained-html --capture=tee-sys
;          --alluredir=reports/allure-results
[pytest]

addopts =
    -v
    --html=reports/report.html
    --self-contained-html
    #--alluredir=reports/allure-results

python_files = test_*.py

python_functions = test_*